### ISSUE TITLE
Updates based on latest Pymunk

### ISSUE THREAD

**Issue by rajsodhi** [estevaofon/angry-birds-python#2]
With some help from a friend named Carson, I got this working using the latest pymunk 5.1.0 package from 'viblo.'  Some function calls in main.py needed updating.
1)  had to convert music to .ogg file
`    song1 = "resources/sounds/angry-birds.ogg"`
2) function call to post_solve_bird_wood needs 3rd argument
`   def post_solve_bird_wood(arbiter, space, data):`
and similarly for 
`def post_solve_pig_wood(arbiter, space, data):`
also note that the order of the input arguments changed between pymunk 4.0.0 and 5.1.0.
3) to implement the collision handler, I was able to make it work with a separate line of code to add the 'post_solve' func.
```
birdPig = space.add_collision_handler(0, 1) #, post_solve=post_solve_bird_pig)
birdPig.post_solve = post_solve_bird_pig
```
4) To avoid killing the kernel in Spyder everytime I exited a game, I added the following lines to the bottom.

```
pygame.display.quit()
pygame.mixer.music.stop()
#os._exit(0)

```

If you let me know how to upload the main.py, I can share my latest version.

Yours,

Raj

**Comment by estevaofon** [comment]
Great! Thanks for the help, it will be nice to update the code. Could you send me a pull request?

**Comment by estevaofon** [comment]
Already updated to the latest Pymunk.
